### ISSUE TITLE
关于typora主题Eva.css

### ISSUE THREAD

**Issue by mushengw** [viridityzhu/Evangelion-typora-theme#1]
若直接使用Eva.css文件，导入主题文件夹后无法使用。
我发现typora主题编写的使用文档中提到
![LWZB1) }LU47SGSKWXE49CB](https://user-images.githubusercontent.com/96338339/146640013-dc82fedd-106e-4028-8e72-32244561f163.png)
所以这里建议将文件名称改为小写eva

**Comment by tarnish233** [comment]
太细了，我刚刚也发现用不了，┭┮﹏┭┮

**Comment by mushengw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by viridityzhu** [comment]
感谢提醒！我已经把`Eva.css`重命名为`eva.css`了
