### ISSUE TITLE
bug perf: 源代码模式下缩进文本几乎不可见

### ISSUE THREAD

**Issue by sun2ot** [viridityzhu/Evangelion-typora-theme#2]
![image](https://user-images.githubusercontent.com/84566015/149704544-9c68489c-90a5-4618-aefa-9268f59f52b0.png)
如图，focus文本实在难以看清，请问css文件中哪部分对应此处的深蓝色字符呢？

**Comment by viridityzhu** [comment]
您好，我已经增加以下代码：

https://github.com/viridityzhu/Evangelion-typora-theme/blob/eb9562201a88bc15496e856734931cd488637b4d/eva.css#L375-L377

效果如下：

![image](https://user-images.githubusercontent.com/39082096/149708512-5d2f4538-3574-4f41-a57c-ed488e6c7ba9.png)

**Comment by sun2ot** [comment]
> 

感谢！

**Comment by viridityzhu** [comment]
感谢提出意见，嘿嘿～
